#!/usr/bin/env python3
"""
2-measure_runtime.py
"""
from typing import List

async_generator = __import__('0-async_generator').async_generator


async def async_comprehension() -> List[float]:
    """
    Uses an asynchronous list comprehension to return a list of numbers
    generated by the async_generator function.

    Returns:
        List[float]: A list of randomly generated floats.
    """
    return [i async for i in async_generator()]
